deployment:
  svc: true
  bff: true
  ui: true

product:
  info:
    data:
      description: "OneCX AI Management"
      imageUrl: ""
      iconName: "lock"
      displayName: "OneCX AI Management"
      basePath: "/ai-management"